const paragraphs = [
    "De todas as pessoas que passaram para o lado das trevas, Sirius Black é o último em que eu pensaria... quero dizer, eu me lembro dele quando era garoto em Hogwarts. Se alguém tivesse me dito, então, no que ele iria se transformar, eu teria respondido que a pessoa tinha bebido quentão demais.",
    "Morrer? Nem um pouco - respondeu Sirius. - Mais rápido e mais fácil do que adormecer.",
    "O mundo não se divide em pessoas boas e más. Todos temos luz e trevas dentro de nós. O que importa é o lado o qual decidimos agir. Isso é o que realmente somos.",
    "Veja, para mim, as memórias são difíceis. Muitas vezes, elas machucam. Uma coisa curiosa sobre o luto é a maneira como isso leva toda a sua vida, todos aqueles anos fundamentais que fizeram de você quem você é, e torna-os tão dolorosos de se olhar para trás por causa da ausência lá, que de repente eles estão inacessíveis. Você deve inventar um sistema inteiramente novo.",
    "Foi há 37 anos o feitiço caiu em mim. Agora, quando falo tenho que cantar assim... Para viver cantando preciso me isolar, por isso essa cabana é meu lar! Quem vive na montanha tem sempre o que temer por isso é bom você se precaver.",
    "Você consegue cheirar isto? Cheire isto? É Napalm, filho. Nada no mundo tem um cheiro semelhante. Adoro o cheiro de napalm pela manhã. Sabe, uma tarde bombardeamos uma colina por doze horas. Quando tudo acabou eu subi a colina. Não encontramos um deles, nem sequer um corpo mal cheiroso. O cheiro, você sabe aquele cheiro de gasolina, toda a colina…. cheirava a vitoria",
    "Ah, mas que aglomeração brilhante, Rei Estevão! Realeza, nobreza, cortesãos e... que graça! Até a ralé! Eu realmente com tristeza estranhei não ter sido convidada. Não sou bem-vinda? Ah, Deus, que terrível situação! Julguei que tivesse sido apenas um descuido... bem, sendo assim é melhor que eu me vá. Oh, não... não estou ofendida, majestade! E, provando o que lhe digo, eu também vou agraciar a criança. Ouçam bem, todos vocês! A princesa crescerá em graça e beleza e amada por aqueles que a conheçam. Mas... antes do pôr do sol do seu décimo sexto aniversário ela picará o dedo no fuso de uma roca e morrerá!",
    "Você quer super-heróis para protegê-lo e torná-lo ainda mais fraco, por mesma ocasião. Você pensa que está protegido, que seus interesses são atendidos, que seus direitos são defendidos. Mas o sistema continua a roubá-lo, e com um sorriso. Então vá em frente, envie seus super-heróis para me impedir. Pegue suas fichas, ligue suas telas e veja o que vai acontecer. Você não está mais no controle. Eu estou"
]